deal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('edit-template/<str:field_name>/', views.edit_deal_template, name="edit_deal_template"),
    path("deal_list/", views.deal_list, name="deal_list"),
    path("deal-template/add/", views.add_deal_template_field, name="add_deal_template_field"),
    path("deal-template/delete/<str:field_name>/", views.delete_deal_template_field, name="delete_deal_template_field"),
]

lead/urls.py
from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import LeadViewSet, ContactViewSet

router = DefaultRouter()
router.register(r'leads', LeadViewSet, basename='lead')
router.register(r'contacts', ContactViewSet, basename='contact')



urlpatterns = [
    path('add-lead/', views.add_lead, name='add_lead'),
    path('add-lead-public/<uuid:invite_token>/', views.add_lead_public, name='add_lead_public'),
    path('', views.leads_list, name='leads_list'),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path('<int:pk>/edit/', views.leads_edit, name='leads_edit'),
    path('<int:pk>/', views.leads_detail, name='leads_detail'),
    path('<int:pk>/add-contact/', views.add_contact, name='add_contact'),
    path('contact/<int:pk>/delete/', views.delete_contact, name='delete_contact'),
    path('contact/<int:pk>/edit/', views.contact_edit, name='contact_edit'),
    path('<int:pk>/pdf/', views.lead_pdf, name='lead_pdf'),
    path('send-client-email/<int:pk>/', views.send_client_email, name='send_client_email'), 
    path('', include(router.urls)),

]

tealcrm/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from core.views import index, about
from userprofile.views import signup
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

handler400 = "core.views.error_400"
handler403 = "core.views.error_403"
handler404 = "core.views.error_404"
handler500 = "core.views.error_500"


urlpatterns = [
    path('',index, name='index'),
    path('leads/', include('lead.urls')),
    path('deal/', include('deal.urls')),
    path('about/', about, name='about'),
    path('sign-up/', signup, name='signup'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'),name='login'),
    path('log-out/', LogoutView.as_view(next_page='', http_method_names=['get', 'post']), name='logout'),
    path('admin/', admin.site.urls),
    path('profile/', include('userprofile.urls')),
    path('api/', include('lead.urls')),
    path('api-auth/', include('rest_framework.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lead/models.py
from operator import concat
from django.db import models
from django.contrib.auth.models import User

class Lead(models.Model):
    
    DAYS = [
        ('א','א'),
        ('ב','ב'),
        ('ג','ג'),
        ('ד','ד'),
        ('ה','ה'),
        ('ו','ו'),
    ]

    HEBREW_MONTHS = [
    ('תשרי', 'תשרי'),
    ('חשוון', 'חשוון'),
    ('כסלו', 'כסלו'),
    ('טבת', 'טבת'),
    ('שבט', 'שבט'),
    ('אדר', 'אדר'),
    ('ניסן', 'ניסן'),
    ('אייר', 'אייר'),
    ('סיון', 'סיון'),
    ('תמוז', 'תמוז'),
    ('אב', 'אב'),
    ('אלול', 'אלול'),
    ]
    STATUS_CHOICES = [
    ('contacted', 'יצר קשר'),
    ('closed', 'סגר עסקה'),
    ('served', 'קיבל שירות'),
    ]

    PAYMENT_STATUS_CHOICES = [
    ('unpaid', 'לא שילם'),
    ('partial', 'שילם חלקית'),
    ('paid', 'שילם במלואו'),
    ]
    PAYMENT_METHOD = [
    ('credit-card', 'אשראי'),
    ('bank-transfer', 'העברה בנקאית'),
    ('cash', 'מזומן'),
    ]
    bride_side = models.CharField(verbose_name="משפחת הכלה", max_length=20)
    groom_side = models.CharField(verbose_name="משפחת החתן", max_length=20)
    address = models.CharField(verbose_name="כתובת האולם", max_length=40, blank=True, default="")
    day = models.CharField(verbose_name="יום", max_length=1, choices=DAYS, blank=True, default="")
    hebrew_day = models.CharField(verbose_name="יום עברי", max_length=10, blank=True, default="")
    hebrew_month = models.CharField(verbose_name="חודש עברי", max_length=10, choices=HEBREW_MONTHS, blank=True, default="")
    hebrew_year = models.CharField(verbose_name="שנה עברית", max_length=10, blank=True, default="")
    date_gregorian = models.DateField(verbose_name="תאריך לועזי", null=True, blank=True)
    hour = models.CharField(verbose_name="שעה", max_length=10,blank=True, default="לא נקבע")
    hall = models.CharField(max_length=255, verbose_name="אולם", blank=True, default="")
    additional_details = models.TextField(verbose_name="פרטים נוספים", blank=True, default="")
    additional_crew = models.CharField(verbose_name="צלמת",max_length=50, blank=True, null=True, default="")
    has_additional_crew = models.BooleanField(verbose_name="רוצים צלמת בנוסף?", default=False)
    video = models.CharField(verbose_name="וידאו",max_length=50, blank=True, default="❓")
    assistent = models.CharField(verbose_name="עוזר",max_length=50, blank=True, default="❓")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='contacted')
    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='unpaid')
    payment_method = models.CharField(verbose_name="אמצעי תשלום",max_length=20, choices=PAYMENT_METHOD, default='')
    custom_fields = models.JSONField(default=dict, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.bride_side} - {self.groom_side} - {self.date_gregorian}"

class Contact(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, related_name='contacts')
    first_name = models.CharField(verbose_name="שם פרטי", max_length=100, default="")
    second_name = models.CharField(verbose_name="שם משפחה", max_length=100, default="")
    phone = models.CharField(verbose_name="טלפון", max_length=20,blank=True, null=True)
    email = models.EmailField(verbose_name="אימייל", blank=True, null=True)
    role = models.CharField(verbose_name="קשר לבעלי השמחה:", max_length=50, blank=True, null=True)
    concat_address = models.CharField(verbose_name="כתובת", max_length=50, blank=True, null=True)

    def __str__(self):
        full_name = f"{self.first_name} {self.second_name}".strip()
        return f"{full_name} ({self.role})"

lead/views.py
from django.contrib import messages
from django.db.models import Q, Value
from django.db.models.functions import Concat
from django.contrib.auth.decorators import login_required
from .forms import AddLeadForm, AddLeadFormPublic, ContactFormSet, ContactFormSetPublic
from django.shortcuts import get_object_or_404, render, redirect
from itertools import groupby
from .forms import AddLeadForm, AddContactForm
from .models import Lead, Contact
from userprofile.models import Userprofile
from django.template.loader import render_to_string
from django.http import HttpResponse
from weasyprint import HTML , CSS
from django.templatetags.static import static
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from .serializers import LeadSerializer, ContactSerializer
from lead.tasks import send_lead_pdf_task
import logging
logger = logging.getLogger(__name__)


class LeadViewSet(viewsets.ModelViewSet):
    queryset = Lead.objects.all().order_by("-id")
    serializer_class = LeadSerializer
    permission_classes = [IsAuthenticated]   

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)


class ContactViewSet(viewsets.ModelViewSet):
    queryset = Contact.objects.all().order_by("-id")
    serializer_class = ContactSerializer
    permission_classes = [IsAuthenticated]

@login_required
def leads_list(request):
    query = request.GET.get('q', '').strip()
    leads = Lead.objects.filter(created_by=request.user).order_by('date_gregorian')
   
    if query:
       
        leads = leads.annotate(
            full_hebrew_date=Concat(
                'hebrew_day', Value(' '),
                'hebrew_month', Value(' '),
                'hebrew_year'
            )
        ).filter(
            Q(bride_side__icontains=query) |
            Q(groom_side__icontains=query) |
            Q(date_gregorian__icontains=query) |
            Q(hebrew_day__icontains=query) |
            Q(hebrew_month__icontains=query) |
            Q(hebrew_year__icontains=query) |
            Q(full_hebrew_date__icontains=query) | 
            Q(contacts__first_name__icontains=query) |
            Q(contacts__second_name__icontains=query) |
            Q(contacts__phone__icontains=query) |
            Q(contacts__email__icontains=query)
        ).distinct()
    

    leads = list(leads)
    
    # deviding leads by the month of the event
    grouped_leads = {}
    for key, group in groupby(
        leads,
        key=lambda l: (l.hebrew_year, l.hebrew_month)):
        
        grouped_leads[key] = list(group)
        
       

    # colors by the month
    month_colors = {
        "תשרי": "bg-blue-100",
        "חשוון": "bg-purple-100",
        "כסלו": "bg-green-100",
        "טבת": "bg-yellow-100",
        "שבט": "bg-pink-100",
        "אדר": "bg-indigo-100",
        "ניסן": "bg-orange-100",
        "אייר": "bg-teal-100",
        "סיון": "bg-lime-100",
        "תמוז": "bg-rose-100",
        "אב": "bg-emerald-100",
        "אלול": "bg-cyan-100",
    }

    for lead in leads:
        if lead.date_gregorian:
            base_color = month_colors.get(lead.hebrew_month, "bg-gray-100")
            week_number = (lead.date_gregorian.day - 1) // 7
            opacity = 100 - (week_number * 15)
            lead.color_class = f"{base_color} opacity-{opacity}"
        else:
            lead.color_class = "bg-gray-100"
    
    return render(request, 'lead/leads_list.html', {
        'leads': leads,
        'query': query,
        'grouped_leads': grouped_leads,
    })

@login_required
def leads_detail(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    contacts = lead.contacts.all()
    custom_fields = get_client_fields(request.user, lead)

    return render(request, 'lead/leads_detail.html', {
        'lead': lead,
        'contacts': contacts,
        'fields': custom_fields,
    })

@login_required
def leads_delete(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead.delete()

    messages.success(request, "הלקוח נמחק בהצלחה")

    return redirect('leads_list')

@login_required
def delete_contact(request, pk):
    contact = get_object_or_404(Contact, id=pk, lead__created_by=request.user)
    lead_id = contact.lead.id  

    contact.delete()
    messages.success(request, "איש הקשר נמחק בהצלחה!")

    return redirect('leads_detail', pk=lead_id)
    
@login_required
def add_lead(request):
    userprofile, created = Userprofile.objects.get_or_create(user=request.user)
    template_fields = userprofile.fields or {}

    if request.method == 'POST':
        form = AddLeadForm(request.POST)
        formset = ContactFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user

            custom_values = {}
            for key, info in template_fields.items():
                custom_values[key] = request.POST.get(key, "")
            lead.custom_fields = custom_values

            lead.save()

            contacts = formset.save(commit=False)
            for contact in contacts:
                contact.lead = lead
                contact.save()

            messages.success(request, "הלקוח נוצר בהצלחה")

            return redirect('leads_list')
    else:
        form = AddLeadForm()
        formset = ContactFormSet()
    return render(request, 'lead/add_lead.html', {
        'form': form,
        'formset': formset,
        'fields': template_fields
    })

def add_lead_public(request, invite_token):

    userprofile = get_object_or_404(Userprofile, invite_token=invite_token)

    if request.method == 'POST':
        form = AddLeadFormPublic(request.POST)

        bride_form = AddContactForm(request.POST, role="כלה", hide_role=True, prefix="bride")
        groom_form = AddContactForm(request.POST, role="חתן", hide_role=True, prefix="groom")

        formset = ContactFormSetPublic(request.POST)

        if form.is_valid() and bride_form.is_valid() and groom_form.is_valid() and formset.is_valid():

            lead = form.save(commit=False)
            lead.created_by = userprofile.user  
            lead.status = 'יצר קשר'
            lead.payment_status = 'לא שילם'

            if lead.has_additional_crew and not lead.additional_crew:
                lead.additional_crew = "❓"

            lead.save()

            
            bride = bride_form.save(commit=False)
            bride.lead = lead
            bride.save()

            
            groom = groom_form.save(commit=False)
            groom.lead = lead
            groom.save()

            
            extra_contacts = formset.save(commit=False)
            for c in extra_contacts:
                c.lead = lead
                c.save()

            return render(request, 'lead/thanks.html', {'lead': lead})

    else:
        form = AddLeadFormPublic()
        bride_form = AddContactForm(role="כלה", hide_role=True, prefix="bride")
        groom_form = AddContactForm(role="חתן", hide_role=True, prefix="groom")
        formset = ContactFormSetPublic()

    return render(request, 'lead/add_lead_public.html', {
        'form': form,
        'bride_form': bride_form,
        'groom_form': groom_form,
        'formset': formset,
        'userprofile': userprofile,
    })


@login_required
def contact_edit(request, pk):
    contact = get_object_or_404(Contact, id=pk, lead__created_by=request.user)
    lead_id = contact.lead.id 

    if request.method == 'POST':
        form = AddContactForm(request.POST, instance=contact)

        if form.is_valid():
            form.save()

            messages.success(request, "פרטי איש הקשר נערכו בהצלחה")

            return redirect('leads_detail', pk=lead_id)
    else:
        form = AddContactForm(instance=contact)
    return render(request, 'lead/add_contact.html', {
        'form': form,
        'contact': contact
    })

@login_required
def add_contact(request, pk):
    lead = get_object_or_404(Lead, id=pk, created_by=request.user)

    if request.method == 'POST':
        form = AddContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.lead = lead
            contact.save()
            messages.success(request, "איש הקשר נוסף בהצלחה!")
            return redirect('leads_detail', pk=pk)
    else:
        form = AddContactForm()

    return render(request, 'lead/add_contact.html', {'form': form, 'lead': lead})


def get_client_fields(user, lead):
    userprofile, _ = Userprofile.objects.get_or_create(user=user)

    # אם השדות נשמרים ישירות ב-userprofile
    template_fields = getattr(userprofile, "fields", {})

    client_data = lead.custom_fields or {}

    merged = {}
    for key, info in template_fields.items():
        value = client_data.get(key, info.get("default"))
        if isinstance(value, str):
            if value in ["true", "True", "1", True]:
                value = "כן"
            elif value in ["false", "False", "0", False]:
                value = "לא"
        merged[key] = {
            "label": info.get("label"),
            "type": info.get("type"),
            "value": value,
        }
    return merged
    
@login_required
def leads_edit(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    userprofile, _ = Userprofile.objects.get_or_create(user=request.user)
    template_fields = getattr(userprofile, "fields", {})

    if request.method == 'POST':
        form = AddLeadForm(request.POST, instance=lead)

        if form.is_valid():
            new_values = {}
            for key in template_fields.keys():
                if key in request.POST:
                    new_values[key] = request.POST.get(key)
            lead.custom_fields = new_values
            form.save()
            
            
            messages.success(request, "פרטי הלקוח נערכו בהצלחה")
            return redirect('leads_list')
    
    else:

lead/templates/lead/add_contact.html
{% extends 'core/base.html' %}

{% block title %}Add Contact{%endblock%}

{% block content %}
    <div class="py-6 px-6">
      <h1 class="text-xl">הוסף או ערוך איש קשר ללקוח</h1>

      <form method="post" action=".">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">אישור</button>
      </form>
    </div>
      
{%endblock%}

lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}

{% block title %}Add Lead{% endblock %}

{% block content %}
{% load custom_filters %}

<div class="py-6 px-6">
  <h1 class="text-xl">הוסף לקוח</h1>

  <form method="post" action=".">
    {% csrf_token %}

    <div class="mb-6 bg-white shadow rounded-xl p-4">
      <h2 class="text-lg font-semibold mb-3">פרטי לקוח</h2>
      {{ form.as_p }}
    </div>

    <div class="mb-6 bg-white shadow rounded-xl p-4">
      <h2 class="text-lg font-semibold mb-3">הוסף אנשי קשר</h2>
      <p class="text-gray-400 text-sm mb-10 italic">
        כדאי להוסיף גם את החתן והכלה כאנשי קשר ובקשר לבעלי השמחה לכתוב חתן עבור החתן או כלה עבור הכלה
    </p>
      {{ formset.management_form }}
      {% for contact_form in formset %}
        <div class="border p-3 mb-3 rounded-lg bg-gray-50">
          {{ contact_form.as_p }}
        </div>
      {% endfor %}
    </div>

    <div class="mb-6 bg-white shadow rounded-xl p-4">
      <h2 class="text-lg font-semibold mb-3">שדות מותאמים אישית</h2>

      {% for key, info in fields.items %}
        <div class="form-group mb-4">
          <label for="{{ key }}" class="block font-medium mb-1">{{ info.label }}</label>

          {% if info.type == "boolean" %}
            <select name="{{ key }}" id="{{ key }}" class="border p-2 rounded w-full">
              <option value="">בחר...</option> 
              <option value="True" {% if info.value == "True" %}selected{% endif %}>כן</option>
              <option value="False" {% if info.value == "False" %}selected{% endif %}>לא</option>
            </select>
          {% else %}
            <input 
              type="{{ info.type|default:'text' }}" 
              name="{{ key }}" 
              id="{{ key }}" 
              class="form-control p-2 w-full border rounded"
              value="{{ info.default|default:'' }}">
          {% endif %}
        </div>
      {% endfor %}
    </div>

    <button type="submit" class="py-4 px-8 bg-teal-500 text-white rounded-xl">
      הוסף לקוח
    </button>
  </form>
</div>
{% endblock %}

lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %}

{% block title %}Add Lead{%endblock%}

{% block content %}
    <div class="py-8 px-8 space-y-8">

        <h1 class="text-2xl font-bold text-center mb-6">
           {{ lead.bride_side }} - {{ lead.groom_side }}
        </h1>
      
        
        <div class="bg-gray-100 rounded-xl shadow p-6">
          <h2 class="text-xl font-semibold mb-4 border-b border-gray-300 pb-2">פרטי האירוע</h2>
      
          <div class="grid grid-cols-2 gap-x-8 gap-y-4">
            <div>
              <p class="font-semibold">סטטוס עסקי:</p>
              <p>{{ lead.get_status_display }}</p>
            </div>
      
            <div>
              <p class="font-semibold">סטטוס תשלום:</p>
              <p>{{ lead.get_payment_status_display }}</p>
            </div>

            <div>
              <p class="font-semibold">אמצעי תשלום:</p>
              <p>{{ lead.get_payment_method_display }}</p>
            </div>

            <div>
              <p class="font-semibold">יום האירוע:</p>
              <p>{{ lead.get_day_display }}</p>
            </div>

            <div>
              <p class="font-semibold">שעת האירוע:</p>
              <p>{{ lead.hour }}</p>
            </div>
      
            <div>
              <p class="font-semibold">תאריך עברי:</p>
              <p>{{ lead.hebrew_day }} {{ lead.get_hebrew_month_display }} {{ lead.hebrew_year }}</p>
            </div>
      
            <div>
              <p class="font-semibold">תאריך לועזי:</p>
              <p>{{ lead.date_gregorian }}</p>
            </div>
      
            <div>
              <p class="font-semibold">אולם:</p>
              <p>{{ lead.hall }}</p>
            </div>
      
            <div>
              <p class="font-semibold">כתובת אולם:</p>
              <p>{{ lead.address }}</p>
            </div>
      
            <div class="col-span-2">
              {% if lead.has_additional_crew %}
                 <p class="font-semibold">צלמת:</p>
                 <p>{{ lead.additional_crew }}</p>
              {% else %}
                 <p>לא ביקשו צלמת</p>
              {% endif %}
            </div>
      
            <div>
              <p class="font-semibold">וידאו:</p>
              <p>{{ lead.video }}</p>
            </div>

            <div>
              <p class="font-semibold">עוזר:</p>
              <p>{{ lead.assistent }}</p>
            </div>

            <div class="col-span-2">
              <p class="font-semibold">פרטים נוספים:</p>
              <p>{{ lead.additional_details |default:"אין פרטים נוספים" }}</p>
            </div>
          </div>
        </div>
        {% if lead.custom_fields %}
        <div class="bg-gray-100 rounded-xl shadow p-6 mt-6">
          <h2 class="text-xl font-semibold mb-4 border-b border-gray-300 pb-2">חבילת עסקה</h2>
      
          <div class="grid grid-cols-2 gap-x-8 gap-y-4">
            {% for key, field in fields.items %}
              <div>
                 <p class="font-semibold">{{ field.label }}:</p>
                 <p>{{ field.value|default:"—" }}</p>
              </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        <div class="bg-gray-100 rounded-xl shadow p-6 mt-6">
          <h2 class="text-xl font-semibold mb-4 border-b border-gray-300 pb-2">אנשי קשר</h2>
        
          {% if contacts %}
            {% for contact in contacts %}
              <div class="border rounded-lg p-4 mb-4 bg-white flex justify-between items-start">
                <div>
                     <p><strong>שם פרטי:</strong> {{ contact.first_name }}</p>
                     <p><strong>שם משפחה:</strong> {{ contact.second_name }}</p>
                     <p><strong>טלפון:</strong> {{ contact.phone }}</p>
                     <p><strong>אימייל:</strong> {{ contact.email|default:"—" }}</p>
                     <p><strong>כתובת:</strong> {{ contact.concat_address|default:"—" }}</p>
                     <p><strong>קשר לבעלי השמחה:</strong> {{ contact.role|default:"—" }}</p>
                </div>
                <div>
                     <a href="{% url 'delete_contact' contact.id %}" 
                      onclick="return confirm('האם למחוק את איש הקשר?')"
                      class="text-red-600 hover:text-red-800 font-semibold">
                      מחק ✖
                    </a>
                </div>
                <div>
                    <a href="{% url 'contact_edit' contact.id %}" 
                     class="text-green-600 hover:text-green-800 font-semibold">
                     ערוך
                    </a>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <p>לא קיימים אנשי קשר ללקוח זה.</p>
          {% endif %}
        </div>
              
        
        <hr class="my-4">

        <a href="{% url 'leads_delete' lead.id%}"
        onclick="return confirm('האם למחוק את הלקוח?')"
        class="py-2 px-4 rounded-xl bg-red-500 text-white">מחק לקוח
        </a>
        <a href="{% url 'leads_edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">ערוך לקוח</a>
        <a href="{% url 'add_contact' lead.id%}" class="py-2 px-4 rounded-xl bg-teal-300 text-white">הוסף איש קשר</a>


        <hr class="my-4">
        <a href="{% url 'leads_list' %}" class="py-2 px-4 rounded-xl bg-gray-500 text-white">חזור לרשימת הלקוחות</a>
    </div>
{%endblock%}

lead/templates/lead/leads_list.html
{% extends 'core/base.html' %}

{% block title %}רשימת לקוחות{% endblock %}

{% block content %}
<div class="py-8 px-8 bg-gray-50 min-h-screen">
    <h1 class="text-2xl font-bold mb-6 text-teal-700 border-b-2 border-teal-500 inline-block pb-1">
        רשימת לקוחות
    </h1>
    <p class="text-gray-400 text-sm italic">
        כדי לראות את הפרטים המלאים של הלקוח ניתן ללחוץ על שם הלקוח
    </p>
    <p class="text-gray-400 text-sm mb-5 italic">
        פרטים שעליך למלא מסומנים בסימן שאלה
    </p>

    <!-- SEARCH -->
    <form method="get" class="mb-6 flex gap-3">
        <input type="text" name="q" placeholder="חפש לקוח..."
               class="border border-gray-300 rounded-lg px-3 py-2 flex-1 focus:outline-none focus:ring-2 focus:ring-teal-400"
               value="{{ query }}">
        <button type="submit"
                class="bg-teal-600 hover:bg-teal-700 text-white px-5 py-2 rounded-lg shadow-sm">
            חיפוש
        </button>
    </form>

    
    <a href="{% url 'add_lead' %}"
       class="inline-block px-6 py-2 mb-6 bg-teal-500 hover:bg-teal-600 rounded-xl text-white shadow-md transition">
        ➕ הוסף לקוח
    </a>

    <!-- LEADS TABLE -->
    <div class="overflow-x-auto bg-white rounded-2xl shadow">
        <table class="min-w-full text-center border-collapse">
            <thead class="bg-gray-100 border-b border-gray-300 text-gray-700 font-semibold">
                <tr>
                    <th class="py-3 px-2">בעלי השמחה</th>
                    <th>יום</th>
                    <th>תאריך עברי</th>
                    <th>תאריך לועזי</th>
                    <th>שעה</th>
                    <th>אולם</th>
                    <th>צלמת</th>
                    <th>עוזר</th>
                    <th>וידאו</th>
                    <th>סטטוס עסקי</th>
                    <th>סטטוס תשלום</th>
                    <th>הורדה</th>
                    <th>שליחה</th>
                </tr>
            </thead>
            <tbody>
                {% for key,leads_in_group in grouped_leads.items %}
                    {% for lead in leads_in_group %}
                        <tr class="border-b hover:bg-gray-50 {{ lead.color_class }}">
                            <td class="py-2 px-2 font-semibold text-teal-700 hover:text-teal-900">
                                <a href="{% url 'leads_detail' lead.id %}">
                                    {{ lead.bride_side }} - {{ lead.groom_side }}
                                </a>
                            </td>
                            <td>{{ lead.get_day_display }}</td>
                            <td>{{ lead.hebrew_day }} {{ lead.get_hebrew_month_display }} {{ lead.hebrew_year }}</td>
                            <td>{{ lead.date_gregorian|date:"d/m/Y" }}</td>
                            <td>{{ lead.hour }}</td>
                            <td>{{ lead.hall }}</td>
                            <td>{{ lead.additional_crew }}</td>  
                            <td>{{ lead.assistent }}</td>
                            <td>{{ lead.video }}</td>
                            <td>{{ lead.get_status_display }}</td>
                            <td>{{ lead.get_payment_status_display }}</td>
                            <td>
                                <a href="{% url 'lead_pdf' lead.id %}"
                                   onclick="window.location.href = this.href; return false;"
                                   class="bg-green-500 hover:bg-green-600 text-white px-3 py-1 rounded-md text-sm shadow-sm">
                                    הורד PDF
                                </a>
                            </td>
                            <td>
                                <form method="get" action="{% url 'send_client_email' lead.id %}" class="inline">
                                    <button type="submit"
                                            class="bg-sky-500 hover:bg-sky-600 text-white px-3 py-1 rounded-md text-sm shadow-sm">
                                        שלח PDF ללקוח
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="13" class="text-gray-500 py-4">אין עדיין לקוחות בחודש זה...</td>
                        </tr>
                    {% endfor %}
                {% empty %}
                    <tr>
                        <td colspan="13" class="text-gray-500 py-4">אין לקוחות במערכת...</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}